name: test-spack
description: 'Builds a spack package from given spack-spec'
inputs:
  spec:
    description: 'Spack spec syntax'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: sh
      run: |
        apt-get -y update
        apt-get install -y file bzip2 ca-certificates g++ gcc gfortran git gzip lsb-release patch python3 tar unzip xz-utils zstd

    - name: Set up spack
      uses: spack/setup-spack@v3
      with:
        spack_ref: develop

    - name: Install clang-18
      shell: sh
      if: contains(inputs.spec, 'clang@18')
      run: apt-get install -y clang-18

    - name: Add repos
      shell: spack-bash {0}
      run: |
        spack repo add https://github.com/FEniCS/spack-fenics.git
        spack repo add --name scientificcomputing $GITHUB_WORKSPACE/spack_repos/spack_repo/scientificcomputing
        spack config get repos
        spack repo list

    - name: Add cache
      shell: spack-bash {0}
      run: |
         spack mirror add develop https://binaries.spack.io/develop
         spack config add "packages:all:require:['os=ubuntu24.04','target=x86_64_v3']"
         spack buildcache keys --install --trust

    - name: Compiler find
      shell: spack-bash {0}
      run: spack compiler find

    - name: Create env
      shell: spack-bash {0}
      run: spack env create -d ./env

    - name: Add specs
      shell: spack-bash {0}
      run: spack -e ./env add ${{ inputs.spec }}

    - name: Concretize
      shell: spack-bash {0}
      run: |
        spack -e ./env config add concretizer:unify:true
        spack -e ./env concretize -j 4

    - name: Install
      shell: spack-bash {0}
      run: >
        spack -e ./env install -j 4 
        --log-format junit
        --log-file log.xml

    - name: Upload log
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.spec }}-log
        path: log.xml