name: 🤖 CI Matrix

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * MON" # weekly, Mondays 0200

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style-check:
    name: ✨ Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Fetch Spack CI scripts
        uses: actions/checkout@v6
        with:
          repository: spack/spack
          ref: develop
          path: spack-core
      - run: wget https://raw.githubusercontent.com/spack/spack-packages/refs/heads/develop/.github/workflows/requirements/style/requirements.txt
      - run: wget https://raw.githubusercontent.com/spack/spack-packages/refs/heads/develop/pyproject.toml
      - run: wget https://raw.githubusercontent.com/spack/spack-packages/refs/heads/develop/.ci/style_check.sh
      - run: pip install -r requirements.txt
      - run: chmod +x style_check.sh
      - run: ./style_check.sh HEAD^

  generate-matrix:
    name: ⚙️ Generate Test Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Generate Matrix
        id: set-matrix
        run: python .github/scripts/generate_matrix.py

  test-package:
    needs: [style-check, generate-matrix]
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
        
    name: ${{ matrix.package }}@${{ matrix.version }} ${{ matrix.spec }}
    steps:
      - uses: actions/checkout@v6
        with:
          path: spack_repos
      - uses: ./spack_repos/.github/actions/test-package
        with:
          spec: ${{ matrix.package }}@${{ matrix.version }} ${{ matrix.spec }}
          remote_repos: ${{ matrix.remote_repos }}

      - name: Import test
        shell: spack-bash {0}
        run: |
          spack env activate ./env
          python -c "import ${{ matrix.import_name }}"

      - name: Run tests (scifem only)
        if: matrix.package == 'py-scifem'
        shell: spack-bash {0}
        run: |
          spack env activate ./env
          spack install --add py-pytest
          spack stage ${{ matrix.package }}@${{ matrix.version }} ${{ matrix.spec }}
          spack cd ${{ matrix.package }}@${{ matrix.version }} ${{ matrix.spec }}
          python -m pytest
